//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_JobPortalProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Jobs
    {
        public int JobID { get; set; }
        public string JobName { get; set; }
        public string JobType { get; set; }
        public string JobLocation { get; set; }
        public string JobDescription { get; set; }
        public Nullable<System.DateTime> PublishDate { get; set; }
        public Nullable<System.DateTime> LastDate { get; set; }
        public Nullable<bool> JobStatus { get; set; }
        public Nullable<int> NewsPaperID { get; set; }
    
        public virtual tbl_NewsPaper tbl_NewsPaper { get; set; }
    }
}
